php_versions:
  - major: "7"
    minor_versions:
      - minor: "7.4"
        base_os:
          - name: alpine
          - name: bullseye
            default: true
        patch_versions:
          - 7.4.33
  - major: "8"
    minor_versions:
      - minor: "8.0"
        base_os:
          - name: alpine
          - name: bullseye
            default: true
        patch_versions:
          - 8.0.29
          - 8.0.28
      - minor: "8.1"
        base_os:
          - name: alpine
          - name: bookworm
            default: true
        patch_versions:
          - 8.1.23
          - 8.1.22
      - minor: "8.2"
        base_os:
          - name: alpine
          - name: bookworm
            default: true
        patch_versions:
          - 8.2.10
          - 8.2.8
      - minor: 8.3-rc
        base_os:
          - name: alpine
          - name: bookworm
            default: true
        patch_versions:
          - 8.3-rc