php_versions:
  - major: "7"
    minor_versions:
      - minor: "7.4"
        base_os:
          - name: alpine
          - name: bullseye
            default: true
        patch_versions:
          - 7.4.33
  - major: "8"
    minor_versions:
      - minor: "8.0"
        base_os:
          - name: alpine
          - name: bullseye
            default: true
        patch_versions:
          - 8.0.29
          - 8.0.28
      - minor: "8.1"
        base_os:
          - name: alpine
          - name: bookworm
            default: true
        patch_versions:
          - 8.1.23
          - 8.1.22
          - 8.1.24
      - minor: "8.2"
        base_os:
          - name: alpine
          - name: bookworm
            default: true
        patch_versions:
          - 8.2.10
          - 8.2.11
          - 8.2.9
      - minor: "8.3"
        base_os:
          - name: alpine
          - name: bookworm
            default: true
        patch_versions:
          - 8.3.0
      - minor: 8.3-rc
        base_os:
          - name: alpine
          - name: bookworm
            default: true
        patch_versions:
          - 8.3-rc
php_variations:
  - name: cli
    default: true
  - name: fpm
  - name: fpm-nginx
  - name: unit
    supported_os: # PHP doesn't include "embed SAPI" on Alpine (https://github.com/docker-library/php/pull/1355#issuecomment-1352087633)
      - bullseye
      - bookworm